### PR TITLE
[SRVKE-667] Fix kafka removal webhook rejection

### LINKED ISSUE #1308: Unable to remove KnativeKafka CR
**Describe the bug**
Unable to delete the `KnativeKafka` custom resource (CR) while cleaning up the namespace 'knative-eventing'.

**Version**
Red Hat OpenShift Container Platform
Openshift Serverless version: 1.18.0
OpenShift version: 4.9.6
Kubernetes version: v1.22.1+d8c4430
Channel: candidate-4.9

**How to reproduce**
1. Remove `KnativeEventing` CR via OCP UI in namespace `knative-eventing`
2. Try Remove `KnativeKafka` CR via OCP UI (unresponsive, no effect)
3. Manual remove via oc cli: `oc delete KnativeKafka <NAME_OF_KNATIVE_KAFKA_CR> -n knative-eventing` (no effect)
4. Final cleanup of anything else: `oc delete deploy,svc,cm,secret --all -n knative-eventing`
5. Try namespace delete `oc delete ns knative-eventing` (perpetual `terminating` state)

**Potential root cause (suspicion):**
The finalizer implemented, relies on KnativeEventing CR and does not fully comply to https://kubernetes.io/docs/concepts/architecture/garbage-collection/. It is not apparent when deleting KnativeEventing CR, that KnativeKafka CR is reliant on it. 

I did try to remove the finalizer from the cr and got the following message:
```
oc replace -f /tmp/oc-edit-2388570947.yaml
Error from server (KnativeEventing instance must be installed before KnativeKafka): error when replacing "/tmp/oc-edit-2388570947.yaml": admission webhook "validating.knativekafkas.operator.serverless.openshift.io" denied the request: KnativeEventing instance must be installed before KnativeKafka
```

Edit - added output of namespace.status:
```
apiVersion: v1
kind: Namespace
[...]
status:
- lastTransitionTime: "2021-11-16T14:07:43Z"
    message: 'Some resources are remaining: knativekafkas.operator.serverless.openshift.io
      has 1 resource instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2021-11-16T14:07:43Z"
    message: 'Some content in the namespace has finalizers remaining: knative-kafka-openshift
      in 1 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
 ```

### PR DESCRIPTION
**Pull request by skonto**
Fixes #1308.
/cc @aliok

### CODE REVIEW

File: knative-operator/pkg/webhook/knativekafka/webhook_validating.go [hunk 1]
```diff
@@ -109,7 +110,11 @@ func (v *Validator) validateShape(_ context.Context, ke *serverlessoperatorv1alp
 }
 
 // validate that KnativeEventing is installed as a hard dep
-func (v *Validator) validateDependencies(ctx context.Context, ke *serverlessoperatorv1alpha1.KnativeKafka) (bool, string, error) {
+func (v *Validator) validateDependencies(ctx context.Context, ke *serverlessoperatorv1alpha1.KnativeKafka, req admission.Request) (bool, string, error) {
+	// skip check if in deletion phase as Eventing maybe already deleted
+	if req.Operation == admissionv1.Delete {
```
Comment (markusthoemmes) [inline knative-operator/pkg/webhook/knativekafka/webhook_validating.go:115]: I wonder if this works as intended. We're already not specifying delete operations to be handled by the webhooks (see the CSV), so I think it's actually doing an update operation (because it has finalizers, so its only updating the deletionTimestamp).

As such, do we have to handle it that way, i.e. skip validations of `deletionTimestamp` is set?

Comment (skonto) [reply knative-operator/pkg/webhook/knativekafka/webhook_validating.go:115]: Yes supposed to have a finalizer removed when deletion timestamp is set ok. Let me update it.

Comment (skonto) [reply knative-operator/pkg/webhook/knativekafka/webhook_validating.go]: We might have to skip all validations not sure.

Comment (matzew) [reply knative-operator/pkg/webhook/knativekafka/webhook_validating.go]: you mean `validateLoneliness` for instance? yeah, IMO that check is not relevant for deletion.

Comment (skonto) [reply knative-operator/pkg/webhook/knativekafka/webhook_validating.go]: Ok I can refactor it in another PR.

**Comment by matzew** [comment]
/lgtm
/approve

/hold
waiting on @aliok for final review

**Review by aliok — APPROVED** [review]
/lgtm
/approve

Thanks
